// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnbqojgbtqhfzgccjcvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYnFvamdidHFoZnpnY2NqY3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyNDYxMDgsImV4cCI6MjA5ODgyMjEwOH0.RUqu-CJqQ6TWV0VmT_JVIrvX_mI8uoEzohXpMN0nrcM";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);